name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  flutter_spinkit: ^5.2.1
  intl: ^0.17.0
  email_validator: ^3.0.0
  syncfusion_flutter_charts: ^21.2.4
  http: ^1.2.2
  fl_chart: ^0.69.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
          style: normal

  assets:
    - assets/images/blue_purple_gradient.jpg
    - assets/images/gradient.jpg
    - assets/images/bottom.jpg
